replica:
  - 'office0'
#rgbdtum:
#  - 'rgbd_dataset_freiburg3_structure_texture_far'
#eth:
#  - 'table_3'
#kitti:
#  - '04'
#euroc:
#  - 'MH_01_easy'
#monotum:
#  - 'sequence_01'
#tartanair
#  - 'ME001'
#7scenes
#  - 'redkitchen_seq-01'
#  - 'heads_seq-01'