rgbdtum:
  - rgbd_dataset_freiburg1_xyz
  - rgbd_dataset_freiburg2_xyz
  - rgbd_dataset_freiburg2_desk
  - rgbd_dataset_freiburg3_long_office_household
  - rgbd_dataset_freiburg3_nostructure_texture_near_withloop
  - rgbd_dataset_freiburg3_structure_notexture_far
  - rgbd_dataset_freiburg3_structure_notexture_near
  - rgbd_dataset_freiburg3_structure_texture_far
  - rgbd_dataset_freiburg2_desk_with_person
  - rgbd_dataset_freiburg3_sitting_static
  - rgbd_dataset_freiburg3_sitting_xyz
  - rgbd_dataset_freiburg3_walking_static
  - rgbd_dataset_freiburg2_coke
  - rgbd_dataset_freiburg2_dishes
  - rgbd_dataset_freiburg2_flowerbouquet
  - rgbd_dataset_freiburg2_flowerbouquet_brownbackground
  - rgbd_dataset_freiburg2_metallic_sphere
  - rgbd_dataset_freiburg3_cabinet
  - rgbd_dataset_freiburg3_teddy
  # - rgbd_dataset_freiburg3_cabinet_validation
  # - rgbd_dataset_freiburg3_long_office_household_validation
  # - rgbd_dataset_freiburg3_nostructure_texture_near_withloop_validation
  # - rgbd_dataset_freiburg3_structure_notexture_far_validation
  # - rgbd_dataset_freiburg3_structure_notexture_near_validation
  # - rgbd_dataset_freiburg3_structure_texture_far_validation
  # - rgbd_dataset_freiburg3_sitting_static_validation
  # - rgbd_dataset_freiburg3_sitting_xyz_validation
  # - rgbd_dataset_freiburg3_walking_static_validation


# eth:
# - 'table_3'
# 7scenes:
# - 'chess_seq-01'
# euroc:
# - 'V1_01_easy'
# kitti:
# - '04'