exp_config_medium_droidslam:
  Config: config_medium.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: droidslam

exp_config_medium_mast3rslam:
  Config: config_medium.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: mast3rslam

exp_config_medium_dpvo:
  Config: config_medium.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: dpvo

exp_config_medium_orbslam2:
  Config: config_medium.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: orbslam2