exp_demo_dso:
  Config: config_demo.yaml
  NumRuns: 81
  Parameters: {Preset: preset:0, Mode: mode:1}
  VSLAM: dso

exp_demo_orbslam2:
  Config: config_demo.yaml
  NumRuns: 81
  Parameters: {Visualization: Vis:1, Vocabulary_folder: Voc:VSLAM-LAB/VSLAM-Baselines/ORB_SLAM2/Vocabulary}
  VSLAM: orbslam2

#exp_demo_anyfeature:
#  Config: config_demo.yaml
#  NumRuns: 0
#  Parameters: {Visualization: Vis:1, Feature: Feat:brisk48, AnyFeature Path: anyfeat:VSLAM-LAB/VSLAM-Baselines/AnyFeature-VSLAM}
#  VSLAM: anyfeature     

#exp_demo_colmap:
#  Config: config_demo.yaml
#  NumRuns: 1
#  Parameters: {Verbose: verbose:1, matcher_type: matcher_type:sequential, use_gpu: use_gpu:1, max_rgb: max_rgb:50}
#  VSLAM: colmap
#
#exp_demo_glomap:
#  Config: config_demo.yaml
#  NumRuns: 1
#  Parameters: {Verbose: verbose:1, matcher_type: matcher_type:sequential, use_gpu: use_gpu:1, max_rgb: max_rgb:50}
#  VSLAM: glomap

#exp_demo_dust3r:
#  Config: config_demo.yaml
#  NumRuns: 1
#  Parameters: {} # {Verbose: -v}
#  VSLAM: dust3r