exp_config_extreme_mast3rslam:
  Config: config_extreme.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: mast3rslam

exp_config_extreme_droidslam:
  Config: config_extreme.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: droidslam