# exp_antartica_mast3rslam:
#   Config: config_antarctica.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: mast3rslam

# exp_antartica_droidslam:
#   Config: config_antarctica.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: droidslam

# exp_antartica_dpvo:
#   Config: config_antarctica.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: dpvo

# exp_antartica_orbslam2:
#   Config: config_antarctica.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_idx: [0,400000]}
#   Module: orbslam2

# exp_antartica_monogs:
#   Config: config_antarctica.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_idx: [0,400000]}
#   Module: monogs

exp_antartica_glomap:
  Config: config_antarctica.yaml
  NumRuns: 1
  Parameters: {verbose: 1, max_rgb: 1000000, 'matcher_type': 'exhaustive'}
  Module: glomap

# exp_test_graph:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: orbslam2

# exp_test_memory_droid:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_idx: [0,400]}
#   Module: droidslam

# exp_test_memory_orb:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_idx: [0,400]}
#   Module: orbslam2


# exp_test_memory_mast3r:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, rgb_idx: [0,400]}
#   Module: mast3rslam

# exp_test_graph2:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: orbslam2